// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: exec.sql

package linksdb

import (
	"context"
)

const createLink = `-- name: CreateLink :exec
INSERT INTO links (original_url,short_name ,short_url)
values($1,$2,$3)
`

type CreateLinkParams struct {
	OriginalUrl string
	ShortName   string
	ShortUrl    string
}

func (q *Queries) CreateLink(ctx context.Context, arg CreateLinkParams) error {
	_, err := q.db.ExecContext(ctx, createLink, arg.OriginalUrl, arg.ShortName, arg.ShortUrl)
	return err
}

const deleteLink = `-- name: DeleteLink :exec
DELETE from links where id =$1
`

func (q *Queries) DeleteLink(ctx context.Context, id int32) error {
	_, err := q.db.ExecContext(ctx, deleteLink, id)
	return err
}
