// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package linksdb

import (
	"database/sql"
)

type Link struct {
	ID          int32
	OriginalUrl string
	ShortName   sql.NullString
	ShortUrl    string
}
