// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package linksdb

import (
	"context"
)

type Querier interface {
	CreateLink(ctx context.Context, arg CreateLinkParams) (Link, error)
}

var _ Querier = (*Queries)(nil)
