// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package linksdb

import (
	"context"
)

type Querier interface {
	CreateLink(ctx context.Context, arg CreateLinkParams) (Link, error)
	DeleteLink(ctx context.Context, id int32) error
	GetAllLinks(ctx context.Context) ([]Link, error)
	GetLink(ctx context.Context, id int32) (Link, error)
	GetLinkByOriginURL(ctx context.Context, originalUrl string) (Link, error)
	GetLinkByOriginURLExludedID(ctx context.Context, arg GetLinkByOriginURLExludedIDParams) (Link, error)
	GetLinkByShortName(ctx context.Context, shortName string) (Link, error)
	GetLinkByShortNameExcluedeID(ctx context.Context, arg GetLinkByShortNameExcluedeIDParams) (Link, error)
	UpdateLink(ctx context.Context, arg UpdateLinkParams) (Link, error)
}

var _ Querier = (*Queries)(nil)
