// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: read.sql

package linksdb

import (
	"context"
)

const getAllLinks = `-- name: GetAllLinks :many
SELECT id, original_url, short_name, short_url, created_at FROM links
`

func (q *Queries) GetAllLinks(ctx context.Context) ([]Link, error) {
	rows, err := q.db.QueryContext(ctx, getAllLinks)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Link
	for rows.Next() {
		var i Link
		if err := rows.Scan(
			&i.ID,
			&i.OriginalUrl,
			&i.ShortName,
			&i.ShortUrl,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getLink = `-- name: GetLink :one
SELECT id, original_url, short_name, short_url, created_at FROM links where id = ($1)
`

func (q *Queries) GetLink(ctx context.Context, id int32) (Link, error) {
	row := q.db.QueryRowContext(ctx, getLink, id)
	var i Link
	err := row.Scan(
		&i.ID,
		&i.OriginalUrl,
		&i.ShortName,
		&i.ShortUrl,
		&i.CreatedAt,
	)
	return i, err
}

const getLinkByOriginURL = `-- name: GetLinkByOriginURL :one
SELECT id, original_url, short_name, short_url, created_at FROM links where original_url = ($1)
`

func (q *Queries) GetLinkByOriginURL(ctx context.Context, originalUrl string) (Link, error) {
	row := q.db.QueryRowContext(ctx, getLinkByOriginURL, originalUrl)
	var i Link
	err := row.Scan(
		&i.ID,
		&i.OriginalUrl,
		&i.ShortName,
		&i.ShortUrl,
		&i.CreatedAt,
	)
	return i, err
}

const getLinkByOriginURLExludedID = `-- name: GetLinkByOriginURLExludedID :one
SELECT id, original_url, short_name, short_url, created_at FROM links 
where original_url = ($1)
and id != $2
`

type GetLinkByOriginURLExludedIDParams struct {
	OriginalUrl string
	ID          int32
}

func (q *Queries) GetLinkByOriginURLExludedID(ctx context.Context, arg GetLinkByOriginURLExludedIDParams) (Link, error) {
	row := q.db.QueryRowContext(ctx, getLinkByOriginURLExludedID, arg.OriginalUrl, arg.ID)
	var i Link
	err := row.Scan(
		&i.ID,
		&i.OriginalUrl,
		&i.ShortName,
		&i.ShortUrl,
		&i.CreatedAt,
	)
	return i, err
}

const getLinkByShortName = `-- name: GetLinkByShortName :one
SELECT id, original_url, short_name, short_url, created_at FROM links where short_name = ($1)
`

func (q *Queries) GetLinkByShortName(ctx context.Context, shortName string) (Link, error) {
	row := q.db.QueryRowContext(ctx, getLinkByShortName, shortName)
	var i Link
	err := row.Scan(
		&i.ID,
		&i.OriginalUrl,
		&i.ShortName,
		&i.ShortUrl,
		&i.CreatedAt,
	)
	return i, err
}

const getLinkByShortNameExcluedeID = `-- name: GetLinkByShortNameExcluedeID :one
SELECT id, original_url, short_name, short_url, created_at FROM links 
where short_name = ($1)
and id != $2
`

type GetLinkByShortNameExcluedeIDParams struct {
	ShortName string
	ID        int32
}

func (q *Queries) GetLinkByShortNameExcluedeID(ctx context.Context, arg GetLinkByShortNameExcluedeIDParams) (Link, error) {
	row := q.db.QueryRowContext(ctx, getLinkByShortNameExcluedeID, arg.ShortName, arg.ID)
	var i Link
	err := row.Scan(
		&i.ID,
		&i.OriginalUrl,
		&i.ShortName,
		&i.ShortUrl,
		&i.CreatedAt,
	)
	return i, err
}
