version: "2"

run:
  timeout: 5m

linters:
  enable:
     # Основные (должны быть)
    - govet
    - staticcheck
    - errcheck
    
    # Популярные дополнительные
    - unused
    - ineffassign
    
    # Безопасность
    - gosec
    - bodyclose
    - noctx
    
    # Качество кода
    - gocyclo
    - goconst
    - gocritic
    
    # Стиль
    - revive
    - godot
    - godox
    
    # Производительность
    - prealloc
    - wastedassign
    
    # Ошибки
    - errorlint
    - nilerr
    - wrapcheck
 
formatters:
  enable:
    - gofmt 
    - goimports     