# .golangci.yml

run:
  timeout: 5m

linters:
  enable:
    - errcheck
    - govet
    - staticcheck
    - gofmt
    - goimports
    - gosimple
    - ineffassign
    - unused

output:
  format: colored-line-number