version: "2"

run:
  timeout: 5m

linters:
  enable:
    - errcheck
    - govet
    - staticcheck    # включает typecheck автоматически
    - gofmt
    - goimports
    # Дополнительные (по желанию):
    - gosimple
    - ineffassign
    - unused

output:
  format: colored-line-number