// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package visits

import (
	"context"
)

type Querier interface {
	CreateVisit(ctx context.Context, arg CreateVisitParams) (LinkVisit, error)
	GetVisits(ctx context.Context, arg GetVisitsParams) ([]LinkVisit, error)
	GetVisitsCount(ctx context.Context) (int64, error)
}

var _ Querier = (*Queries)(nil)
