// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: read.sql

package visits

import (
	"context"
)

const getVisits = `-- name: GetVisits :many
SELECT id, link_id, created_at, ip, user_agent, status, referer FROM link_visits
LIMIT $1 OFFSET $2
`

type GetVisitsParams struct {
	Limit  int32
	Offset int32
}

func (q *Queries) GetVisits(ctx context.Context, arg GetVisitsParams) ([]LinkVisit, error) {
	rows, err := q.db.QueryContext(ctx, getVisits, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []LinkVisit
	for rows.Next() {
		var i LinkVisit
		if err := rows.Scan(
			&i.ID,
			&i.LinkID,
			&i.CreatedAt,
			&i.Ip,
			&i.UserAgent,
			&i.Status,
			&i.Referer,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getVisitsCount = `-- name: GetVisitsCount :one
SELECT count(id) FROM link_visits
`

func (q *Queries) GetVisitsCount(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, getVisitsCount)
	var count int64
	err := row.Scan(&count)
	return count, err
}
