// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: exec.sql

package visits

import (
	"context"
	"database/sql"
)

const createVisit = `-- name: CreateVisit :one
INSERT INTO link_visits (link_id , ip , user_agent,status)
values($1,$2,$3,$4)
RETURNING id, link_id, created_at, ip, user_agent, status
`

type CreateVisitParams struct {
	LinkID    sql.NullInt32
	Ip        sql.NullString
	UserAgent sql.NullString
	Status    sql.NullInt32
}

func (q *Queries) CreateVisit(ctx context.Context, arg CreateVisitParams) (LinkVisit, error) {
	row := q.db.QueryRowContext(ctx, createVisit,
		arg.LinkID,
		arg.Ip,
		arg.UserAgent,
		arg.Status,
	)
	var i LinkVisit
	err := row.Scan(
		&i.ID,
		&i.LinkID,
		&i.CreatedAt,
		&i.Ip,
		&i.UserAgent,
		&i.Status,
	)
	return i, err
}
