// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: exec.sql

package visits

import (
	"context"
)

const createVisit = `-- name: CreateVisit :one
INSERT INTO link_visits (link_id , ip , user_agent,status, referer)
values($1,$2,$3,$4,$5)
RETURNING id, link_id, created_at, ip, user_agent, status, referer
`

type CreateVisitParams struct {
	LinkID    int32
	Ip        string
	UserAgent string
	Status    int32
	Referer   string
}

func (q *Queries) CreateVisit(ctx context.Context, arg CreateVisitParams) (LinkVisit, error) {
	row := q.db.QueryRowContext(ctx, createVisit,
		arg.LinkID,
		arg.Ip,
		arg.UserAgent,
		arg.Status,
		arg.Referer,
	)
	var i LinkVisit
	err := row.Scan(
		&i.ID,
		&i.LinkID,
		&i.CreatedAt,
		&i.Ip,
		&i.UserAgent,
		&i.Status,
		&i.Referer,
	)
	return i, err
}
