// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package visits

import (
	"database/sql"
)

type LinkVisit struct {
	ID        int32
	LinkID    sql.NullInt32
	CreatedAt sql.NullTime
	Ip        sql.NullString
	UserAgent sql.NullString
	Status    sql.NullInt32
}
