// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package visits

import (
	"time"
)

type LinkVisit struct {
	ID        int32
	LinkID    int32
	CreatedAt time.Time
	Ip        string
	UserAgent string
	Status    int32
	Referer   string
}
